version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: artist-management-nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/artist-management-app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8084:80"
      - "443:443"
    links:
      - php
  php:
    container_name: artist-management-php
    build:
      context: ./docker/php
      args:
        user: user
        uid: 1000
        PHP_VERSION: ${PHP_VERSION}
    user: root
    volumes:
      - ./:/var/www/artist-management-app/
  database:
    image: mariadb
    volumes:
      - ./docker/database:/var/lib/mysql
      - ./_dump:/_dump
    container_name: artist-management-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
